name: ğŸ” Linter Fix

run-name: "ğŸ” Linter Fix - by @${{ github.actor }}"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  statuses: write

jobs:
  Lint:
    name: ğŸ§¹ Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: ğŸ” Lint code base
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_JSON: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
          FIX_POWERSHELL: true

      - name: ğŸ“ Commit and push linting fixes
      # Run only on:
      # - Pull requests
      # - Not on the default branch
        if: github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
