name: ğŸ” Linter

run-name: "ğŸ” Linter - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: 
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  Lint:
    name: ğŸ§¹ Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: ğŸ” Lint code base
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          FILTER_REGEX_INCLUDE: .*src/.*
